INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(40, 'Bulbasaur', 'Seed Pokémon', 'Leech Seed', '20', 'Fire', 'None', '1 Colorless', 44, 1, 1, 1),
(50, 'Charmander', 'Lizard Pokémon', 'Ember', '30', 'Water', 'None', '1 Colorless', 46, 1, 2, 1),
(50, 'Squirtle', 'Tiny Turtle Pokémon', 'Bubble', '10', 'Lightning', 'None', '1 Colorless', 63, 1, 3, 1),
(60, 'Pikachu', 'Mouse Pokémon', 'Thunder Jolt', '30', 'Fighting', 'None', '1 Colorless', 58, 1, 4, 1),
(60, 'Jigglypuff', 'Balloon Pokémon', 'Lullaby', '—', 'Fighting', 'Psychic', '1 Colorless', 54, 2, 7, 1),
(90, 'Scyther', 'Mantis Pokémon', 'Slash', '30', 'Fire', 'Fighting', '0', 10, 2, 1, 1),
(100, 'Gengar', 'Shadow Pokémon', 'Nightmare', '30', 'Psychic', 'None', '2 Colorless', 5, 3, 5, 2),
(70, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '20', 'Fighting', 'None', '1 Colorless', 56, 2, 7, 1),
(80, 'Electabuzz', 'Electric Pokémon', 'Thunder Shock', '30', 'Fighting', 'None', '2 Colorless', 20, 1, 4, 1),
(90, 'Hitmonchan', 'Punching Pokémon', 'Special Punch', '40', 'Psychic', 'None', '2 Colorless', 7, 1, 6, 1),
(120, 'Snorlax', 'Sleeping Pokémon', 'Body Slam', '30', 'Fighting', 'None', '4 Colorless', 11, 2, 7, 1),
(70, 'Oddish', 'Weed Pokémon', 'Stun Spore', '20', 'Fire', 'None', '1 Colorless', 58, 2, 1, 1),
(80, 'Nidorino', 'Poison Pin Pokémon', 'Horn Drill', '50', 'Psychic', 'None', '2 Colorless', 36, 1, 6, 2),
(100, 'Nidoking', 'Drill Pokémon', 'Thrash', '60', 'Psychic', 'None', '3 Colorless', 11, 1, 6, 3),
(70, 'Poliwag', 'Tadpole Pokémon', 'Water Gun', '30', 'Lightning', 'None', '1 Colorless', 59, 1, 3, 1),
(90, 'Poliwhirl', 'Tadpole Pokémon', 'Amnesia', '30', 'Lightning', 'None', '2 Colorless', 40, 1, 3, 2),
(120, 'Poliwrath', 'Tadpole Pokémon', 'Whirlpool', '40', 'Lightning', 'None', '3 Colorless', 13, 1, 3, 3),
(60, 'Zubat', 'Bat Pokémon', 'Supersonic', '10', 'Lightning', 'Fighting', '1 Colorless', 57, 3, 6, 1),
(80, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Lightning', 'Fighting', '2 Colorless', 24, 3, 6, 2),
(120, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', 'None', '3 Colorless', 13, 3, 6, 2);
