INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(60, 'Eevee', 'Evolution Pokémon', 'Quick Attack', '20', 'Fighting', 'None', '1 Colorless', 55, 2, 7, 1),
(80, 'Flareon', 'Flame Pokémon', 'Flamethrower', '60', 'Water', 'None', '2 Colorless', 12, 2, 2, 2),
(80, 'Vaporeon', 'Bubble Jet Pokémon', 'Water Gun', '30+', 'Lightning', 'None', '2 Colorless', 28, 2, 3, 2),
(80, 'Jolteon', 'Lightning Pokémon', 'Pin Missile', '20x', 'Fighting', 'None', '1 Colorless', 26, 2, 4, 2),
(70, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '20', 'Fighting', 'None', '1 Colorless', 56, 2, 7, 1),
(90, 'Persian', 'Classy Cat Pokémon', 'Slash', '30', 'Fighting', 'None', '2 Colorless', 42, 2, 7, 2),
(100, 'Kangaskhan', 'Parent Pokémon', 'Comet Punch', '20x', 'Fighting', 'None', '3 Colorless', 5, 2, 7, 1),
(60, 'Cubone', 'Lonely Pokémon', 'Bone Attack', '20', 'Grass', 'None', '1 Colorless', 50, 2, 6, 1),
(90, 'Marowak', 'Bone Keeper Pokémon', 'Bonemerang', '30x', 'Grass', 'None', '2 Colorless', 39, 2, 6, 2),
(70, 'Oddish', 'Weed Pokémon', 'Stun Spore', '20', 'Fire', 'None', '1 Colorless', 58, 2, 1, 1),
(80, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '30', 'Fire', 'None', '2 Colorless', 36, 2, 1, 2),
(100, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', 'None', '2 Colorless', 15, 2, 1, 3),
(60, 'Zubat', 'Bat Pokémon', 'Supersonic', '10', 'Lightning', 'Fighting', '1 Colorless', 57, 3, 6, 1),
(80, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Lightning', 'Fighting', '2 Colorless', 24, 3, 6, 2),
(120, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', 'None', '3 Colorless', 13, 3, 6, 2),
(90, 'Aerodactyl', 'Fossil Pokémon', 'Wing Attack', '30', 'Lightning', 'Fighting', '2 Colorless', 1, 3, 6, 1),
(100, 'Kabuto', 'Shellfish Pokémon', 'Scratch', '20', 'Grass', 'None', '1 Colorless', 50, 3, 6, 1),
(120, 'Kabutops', 'Shellfish Pokémon', 'Slash', '40', 'Grass', 'None', '2 Colorless', 9, 3, 6, 2),
(100, 'Omanyte', 'Spiral Pokémon', 'Water Gun', '10+', 'Grass', 'None', '1 Colorless', 52, 3, 3, 1),
(120, 'Omastar', 'Spiral Pokémon', 'Hydro Pump', '30+', 'Grass', 'None', '2 Colorless', 10, 3, 3, 2),
(90, 'Lapras', 'Transport Pokémon', 'Water Gun', '10+', 'Lightning', 'None', '2 Colorless', 20, 3, 3, 1),
(70, 'Krabby', 'River Crab Pokémon', 'Vice Grip', '10', 'Lightning', 'None', '1 Colorless', 51, 3, 3, 1),
(90, 'Kingler', 'Pincer Pokémon', 'Crabhammer', '40', 'Lightning', 'None', '2 Colorless', 34, 3, 3, 2),
(80, 'Geodude', 'Rock Pokémon', 'Tackle', '10', 'Grass', 'None', '1 Colorless', 45, 3, 6, 1),
(100, 'Graveler', 'Rock Pokémon', 'Rock Throw', '40', 'Grass', 'None', '2 Colorless', 36, 3, 6, 2),
(120, 'Golem', 'Megaton Pokémon', 'Explosion', '100', 'Grass', 'None', '4 Colorless', 26, 3, 6, 3),
(60, 'Gastly', 'Gas Pokémon', 'Lick', '10', 'Psychic', 'None', '1 Colorless', 33, 3, 5, 1),
(80, 'Haunter', 'Gas Pokémon', 'Hypnosis', '—', 'Psychic', 'None', '2 Colorless', 22, 3, 5, 2),
(100, 'Ditto', 'Transform Pokémon', 'Transform', '—', 'Fighting', 'None', '1 Colorless', 18, 3, 7, 1),
(120, 'Dragonite', 'Dragon Pokémon', 'Slam', '40x', 'Colorless', 'None', '3 Colorless', 4, 3, 7, 3);
