INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(60, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', 'None', '1 Colorless', 43, 1, 5, 1),
(80, 'Kadabra', 'Psi Pokémon', 'Recover', '—', 'Psychic', 'None', '2 Colorless', 32, 1, 5, 2),
(100, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', 'None', '3 Colorless', 1, 1, 5, 3),
(70, 'Machop', 'Superpower Pokémon', 'Low Kick', '20', 'Psychic', 'None', '1 Colorless', 52, 1, 6, 1),
(90, 'Machoke', 'Superpower Pokémon', 'Karate Chop', '50', 'Psychic', 'None', '2 Colorless', 34, 1, 6, 2),
(120, 'Machamp', 'Superpower Pokémon', 'Seismic Toss', '60', 'Psychic', 'None', '3 Colorless', 8, 1, 6, 3),
(60, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', 'None', '1 Colorless', 62, 1, 4, 1),
(80, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', 'None', '2 Colorless', 9, 1, 4, 2),
(70, 'Voltorb', 'Ball Pokémon', 'Tackle', '10', 'Fighting', 'None', '1 Colorless', 67, 1, 4, 1),
(90, 'Electrode', 'Ball Pokémon', 'Explosion', '80', 'Fighting', 'None', '2 Colorless', 21, 1, 4, 2),
(60, 'Diglett', 'Mole Pokémon', 'Dig', '10', 'Grass', 'None', '1 Colorless', 47, 1, 6, 1),
(80, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '70', 'Grass', 'None', '2 Colorless', 19, 1, 6, 2),
(70, 'Sandshrew', 'Mouse Pokémon', 'Scratch', '20', 'Grass', 'None', '1 Colorless', 64, 1, 6, 1),
(90, 'Sandslash', 'Mouse Pokémon', 'Slash', '40', 'Grass', 'None', '2 Colorless', 22, 1, 6, 2),
(60, 'Doduo', 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Lightning', 'None', '1 Colorless', 48, 1, 7, 1),
(90, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '10+', 'Lightning', 'None', '2 Colorless', 24, 1, 7, 2),
(70, 'Pidgey', 'Tiny Bird Pokémon', 'Gust', '10', 'Lightning', 'Fighting', '1 Colorless', 57, 1, 7, 1),
(90, 'Pidgeotto', 'Bird Pokémon', 'Whirlwind', '20', 'Lightning', 'Fighting', '2 Colorless', 22, 1, 7, 2),
(120, 'Pidgeot', 'Bird Pokémon', 'Hurricane', '30', 'Lightning', 'Fighting', '2 Colorless', 8, 1, 7, 3),
(60, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', 'None', '1 Colorless', 61, 1, 7, 1),
(80, 'Raticate', 'Mouse Pokémon', 'Super Fang', '—', 'Fighting', 'None', '1 Colorless', 40, 1, 7, 2),
(70, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', 'None', '1 Colorless', 45, 1, 1, 1),
(80, 'Metapod', 'Cocoon Pokémon', 'Stiffen', '—', 'Fire', 'None', '2 Colorless', 54, 1, 1, 2),
(100, 'Butterfree', 'Butterfly Pokémon', 'Whirlwind', '20', 'Fire', 'None', '1 Colorless', 3, 1, 1, 3),
(60, 'Weedle', 'Hairy Bug Pokémon', 'Poison Sting', '10', 'Fire', 'None', '1 Colorless', 69, 1, 1, 1),
(80, 'Kakuna', 'Cocoon Pokémon', 'Stiffen', '—', 'Fire', 'None', '2 Colorless', 33, 1, 1, 2),
(100, 'Beedrill', 'Poison Bee Pokémon', 'Twineedle', '30x', 'Fire', 'None', '1 Colorless', 9, 1, 1, 3),
(70, 'Clefairy', 'Fairy Pokémon', 'Sing', '—', 'Fighting', 'Psychic', '1 Colorless', 5, 1, 7, 1),
(90, 'Clefable', 'Fairy Pokémon', 'Metronome', '—', 'Fighting', 'Psychic', '2 Colorless', 17, 1, 7, 2),
(120, 'Chansey', 'Egg Pokémon', 'Scrunch', '—', 'Fighting', 'None', '1 Colorless', 3, 1, 7, 1);
